# Generated by Django 2.0.6 on 2018-06-21 21:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adhoc',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=50)),
                ('hours_projected', models.IntegerField()),
                ('hours_actual', models.IntegerField()),
                ('created_date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('created_date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Defect',
            fields=[
                ('id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=50)),
                ('created_date', models.DateField(default=datetime.date.today)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='timesheets.App')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('created_date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Timesheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('hours', models.DecimalField(decimal_places=2, max_digits=4)),
                ('adhoc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='timesheets.Adhoc')),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='timesheets.App')),
                ('defect', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='timesheets.Defect')),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='timesheets.Employee')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='timesheets.Task')),
            ],
        ),
    ]
