# Generated by Django 2.0.6 on 2018-06-22 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adhoc',
            name='hours_projected',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='adhoc',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='timesheets.Adhoc'),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='defect',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='timesheets.Defect'),
        ),
    ]
